### ISSUE TITLE
Aktuell?

### ISSUE THREAD

**Issue by RobinDieLegende** [dstahlmann/leitstellenspielautoresolver#2]
Servus ich wollte frage on das Script noch aktuell ist? Bekomme das irgendwie mit den aaos nicht hin :/

**Comment by dstahlmann** [comment]
Hi,
nein, das Script ist nicht mehr aktuell. Ich werde es auch erstmal nicht mehr schaffen, die aktuellen Updates im Spiel für das Script zu berücksichtigen. :(
